import { create } from 'zustand'

const id = {
  nav: { about: "Tentang", experience: "Pengalaman", contact: "Kontak", faq: "FAQ" },
  hero: { greeting: "Halo, saya", name: "Zayidan Muttaqin", role: "Penjualan \u00b7 Kepemimpinan \u00b7 Komunikasi", tagline: "Disiplin, teliti, bertanggung jawab, dan adaptif \u2014 siap berkontribusi secara profesional.", tagline2: "Terbiasa bekerja individu maupun tim dengan orientasi pada hasil dan efisiensi.", tagline3: "Siap berkontribusi secara profesional di posisi yang terbuka.", location: "Banyuwangi, Indonesia", ctaContact: "Hubungi Saya", downloadCV: "Download CV", available: "Tersedia untuk Bekerja", scroll: "GULIR", scrollDown: "Gulir ke bawah" },
  about: { title: "Tentang Saya", bio: "Saya Zayidan Muttaqin, karakter utama: disiplin / teliti / bertanggung jawab / adaptif, dengan pengalaman di bidang Penjualan dan kepemimpinan. Memiliki kemampuan dalam menjual produk, komunikasi, dan managemen waktu.", bio2: "Terbiasa bekerja secara individu maupun tim dengan orientasi pada hasil, target, kualitas, dan efisiensi. Siap berkontribusi secara profesional di posisi yang terbuka pada perusahaan.", sales: { title: "Sales & Retail", desc: "Penjualan, Target, Negosiasi" }, leadership: { title: "Leader", desc: "Kepemimpinan, Manajemen, Tim" }, communication: { title: "Communicator", desc: "Komunikasi, Presentasi, Relasi" }, education: { title: "Pendidikan", school: "SMK Manbaul Ulum", major: "Teknik Kendaraan Ringan", period: "2017 \u2013 2020", score: "Nilai Ijazah: 82.21" }, certifications: { title: "Sertifikasi", subtitle: "Kompetensi Inti", sales: "Penjualan", retail: "Retail", leadership: "Kepemimpinan", communication: "Komunikasi" }, skills: { hardTitle: "Hard Skills", softTitle: "Soft Skills", computer: "Operasi Komputer/Laptop/Gadget", video: "Editing Video (CapCut)", design: "Desain Grafis (Canva)", ai: "AI Prompting", financial: "Pasar Keuangan (Saham, Forex, Komoditas, Crypto)", python: "Python Dasar Fundamental", softwareDev: "Software Development Dasar Fundamental", team: "Kerja Tim", leadership: "Kepemimpinan", communication: "Komunikasi", problem: "Pemecahan Masalah", timeManagement: "Manajemen Waktu", adaptif: "Adaptabilitas", disiplin: "Disiplin", teliti: "Teliti & Bertanggung Jawab", customerFocus: "Fokus Pelanggan", negotiation: "Negosiasi", motivasi: "Motivasi Diri & Tim" } },
  stats: { title: "Statistik", experience: { value: "3+", label: "Tahun Pengalaman" }, hardSkills: { value: "7", label: "Hard Skills" }, softSkills: { value: "11", label: "Soft Skills" }, clients: { value: "100+", label: "Pelanggan Dilayani" } },
  experience: { title: "Pengalaman Kerja", present: "Sekarang" },
  contact: { title: "Hubungi Saya", subtitle: "Tertarik untuk bekerja sama? Kirim pesan dan mari wujudkan ide bersama.", name: "Nama", email: "Email", subject: "Subjek", message: "Pesan", namePlaceholder: "Nama Anda", emailPlaceholder: "email@contoh.com", subjectPlaceholder: "Subjek pesan", messagePlaceholder: "Ceritakan tentang kebutuhan Anda...", send: "Kirim Pesan", sending: "Mengirim...", success: "Pesan berhasil dikirim! Saya akan segera merespons.", error: "Gagal mengirim pesan. Silakan coba lagi.", sendAnother: "Kirim Pesan Lagi", emailLabel: "Email", phoneLabel: "Telepon", locationLabel: "Lokasi", linkedin: "LinkedIn", github: "GitHub", telegram: "Telegram", instagram: "Instagram", discord: "Discord", discordServer: "Server Discord", cvLabel: "Download CV", copied: "Berhasil disalin!", share: "Bagikan Profil", shareText: "Penjualan, Kepemimpinan, Komunikasi \u2014 Portfolio Zayidan Muttaqin", shareTo: "Bagikan ke", copyLink: "Salin Tautan", rateLimitError: "Terlalu banyak pesan. Silakan tunggu sebentar.", mapTitle: "Lokasi Saya", scanToSave: "Pindai untuk simpan kontak", chatTitle: "Chat via WhatsApp", chatGreeting: "Halo! Saya ingin bertanya tentang...", chatSend: "Kirim Pesan" },
  faq: { title: "FAQ", subtitle: "Pertanyaan yang sering diajukan.", q0: "Apa pengalaman kerja Anda?", a0: "Saya memiliki pengalaman 3+ tahun di bidang penjualan ritel dan kepemimpinan tim. Fokus utama saya adalah mencapai target penjualan sambil membangun hubungan jangka panjang dengan pelanggan.", q1: "Apakah Anda terbuka untuk proyek freelance?", a1: "Ya, saya selalu terbuka untuk proyek freelance dan kolaborasi. Silakan hubungi saya melalui formulir kontak untuk mendiskusikan kebutuhan proyek Anda.", q2: "Bagaimana cara menghubungi Anda?", a2: "Anda dapat menghubungi saya melalui formulir kontak di bawah, email, atau LinkedIn. Saya biasanya merespons dalam 24 jam.", q3: "Teknologi apa yang Anda kuasai?", a3: "Saya menguasai operasi komputer, editing video (CapCut), desain grafis (Canva), AI Prompting, dan berbagai platform keuangan digital (saham, forex, crypto).", q4: "Apakah Anda bisa bekerja remote?", a4: "Tentu saja. Saya berpengalaman dalam kolaborasi remote dan terbiasa menggunakan berbagai alat komunikasi digital untuk koordinasi tim yang efektif." },
  techstack: { title: "Tech Stack", subtitle: "Keahlian dan alat yang saya kuasai.", innerRing: "Kompetensi Inti", outerRing: "Alat & Teknologi", sales: "Penjualan", leadership: "Kepemimpinan", communication: "Komunikasi", negotiation: "Negosiasi", capcut: "Video Editing", canva: "Graphic Design", ai: "AI Prompting", finance: "Financial Market", computer: "Computer Ops", python: "Python Fundamental", softwareDev: "Software Dev Fundamental" },
  achievements: { title: "Pencapaian", subtitle: "Badge dan milestone yang telah diraih.", unlocked: "Pencapaian Terbuka", unlockedBadge: "TERBUKA", items: { firstSale: { title: "Penjualan Pertama", desc: "Menyelesaikan deal pertama" }, hundredClients: { title: "100 Pelanggan", desc: "Melayani 100+ pelanggan" }, topPerformer: { title: "Performer Terbaik", desc: "Melebihi target penjualan" }, teamLeader: { title: "Pemimpin Tim", desc: "Memimpin tim menuju sukses" }, negotiator: { title: "Negosiator Handal", desc: "Menguasai keterampilan negosiasi" }, quickLearner: { title: "Pembelajar Cepat", desc: "Beradaptasi dengan AI & alat digital" } } },
  shortcuts: { title: "Pintasan Keyboard", theme: "Ganti Tema", language: "Ganti Bahasa", sections: "Navigasi Bagian", palette: "Palet Perintah" },
  konami: { activated: "\ud83d\udd13 KODE KONAMI DI AKTIFKAN", hackerMode: "HACKER MODE" },
  commandPalette: { title: "Perintah", search: "Cari perintah...", navGroup: "Navigasi", actionsGroup: "Tindakan", goHero: "Ke Beranda", goAbout: "Ke Tentang Saya", goExperience: "Ke Pengalaman", goContact: "Ke Kontak", goFaq: "Ke FAQ", goTechstack: "Ke Tech Stack", goAchievements: "Ke Pencapaian", toggleTheme: "Ganti Tema", switchLang: "Ganti Bahasa", downloadCV: "Unduh CV", scrollTop: "Ke Atas", hint: "\u2191\u2193 Navigasi \u00b7 \u21b5 Pilih \u00b7 Esc Tutup" },
  ambientSound: { tooltip: "Suara Ambient" },
  themeCustomizer: { title: "Tema Warna", presets: "Preset Tema", cyberpunk: "Cyberpunk", bloomberg: "Bloomberg", midnight: "Midnight", cyan: "Neon Cyan", magenta: "Neon Magenta", purple: "Neon Ungu", reset: "Reset" },
  footer: { tagline: "Penjualan \u00b7 Kepemimpinan \u00b7 Komunikasi", rights: "Hak cipta dilindungi.", backToTop: "Kembali ke atas", online: "Online", builtWith: "Dibuat dengan" },
}

const en = {
  nav: { about: "About", experience: "Experience", contact: "Contact", faq: "FAQ" },
  hero: { greeting: "Hello, I'm", name: "Zayidan Muttaqin", role: "Sales \u00b7 Leadership \u00b7 Communication", tagline: "Disciplined, detail-oriented, responsible, and adaptive \u2014 ready to contribute professionally.", tagline2: "Experienced working individually and in teams with a results-oriented mindset.", tagline3: "Ready to contribute professionally in any open position.", location: "Banyuwangi, Indonesia", ctaContact: "Contact Me", downloadCV: "Download CV", available: "Available for Work", scroll: "SCROLL", scrollDown: "Scroll down" },
  about: { title: "About Me", bio: "I'm Zayidan Muttaqin \u2014 disciplined, detail-oriented, responsible, and adaptive \u2014 with experience in Sales and Leadership. Skilled in product selling, communication, and time management.", bio2: "Experienced working both individually and in teams, with a results-oriented mindset focused on targets, quality, and efficiency. Ready to contribute professionally in any open position.", sales: { title: "Sales & Retail", desc: "Selling, Targets, Negotiation" }, leadership: { title: "Leader", desc: "Leadership, Management, Team" }, communication: { title: "Communicator", desc: "Communication, Presentation, Relations" }, education: { title: "Education", school: "SMK Manbaul Ulum", major: "Light Vehicle Engineering", period: "2017 \u2013 2020", score: "Diploma Score: 82.21" }, certifications: { title: "Certifications", subtitle: "Core Competencies", sales: "Sales", retail: "Retail", leadership: "Leadership", communication: "Communication" }, skills: { hardTitle: "Hard Skills", softTitle: "Soft Skills", computer: "Computer/Laptop/Gadget Operation", video: "Video Editing (CapCut)", design: "Graphic Design (Canva)", ai: "AI Prompting", financial: "Financial Market (Stock, Forex, Commodity, Crypto)", python: "Python Basic Fundamental", softwareDev: "Software Development Basic Fundamental", team: "Teamwork", leadership: "Leadership", communication: "Communication", problem: "Problem Solving", timeManagement: "Time Management", adaptif: "Adaptability", disiplin: "Discipline", teliti: "Detail-Oriented & Responsible", customerFocus: "Customer Focus", negotiation: "Negotiation", motivasi: "Self & Team Motivation" } },
  stats: { title: "Statistics", experience: { value: "3+", label: "Years Experience" }, hardSkills: { value: "7", label: "Hard Skills" }, softSkills: { value: "11", label: "Soft Skills" }, clients: { value: "100+", label: "Clients Served" } },
  experience: { title: "Work Experience", present: "Present" },
  contact: { title: "Get In Touch", subtitle: "Interested in working together? Send me a message and let's bring ideas to life.", name: "Name", email: "Email", subject: "Subject", message: "Message", namePlaceholder: "Your Name", emailPlaceholder: "name@example.com", subjectPlaceholder: "Subject of your message", messagePlaceholder: "Tell me about your needs...", send: "Send Message", sending: "Sending...", success: "Message sent successfully! I'll get back to you soon.", error: "Failed to send message. Please try again.", sendAnother: "Send Another Message", emailLabel: "Email", phoneLabel: "Phone", locationLabel: "Location", linkedin: "LinkedIn", github: "GitHub", telegram: "Telegram", instagram: "Instagram", discord: "Discord", discordServer: "Discord Server", cvLabel: "Download CV", copied: "Copied to clipboard!", share: "Share Profile", shareText: "Sales, Leadership, Communication \u2014 Zayidan Muttaqin Portfolio", shareTo: "Share to", copyLink: "Copy Link", rateLimitError: "Too many messages. Please wait a moment.", mapTitle: "My Location", scanToSave: "Scan to save contact", chatTitle: "Chat via WhatsApp", chatGreeting: "Hello! I'd like to ask about...", chatSend: "Send Message" },
  faq: { title: "FAQ", subtitle: "Frequently asked questions.", q0: "What is your work experience?", a0: "I have 3+ years of experience in retail sales and team leadership. My main focus is achieving sales targets while building long-term customer relationships.", q1: "Are you open to freelance projects?", a1: "Yes, I'm always open to freelance projects and collaborations. Please contact me through the contact form to discuss your project needs.", q2: "How can I contact you?", a2: "You can reach me through the contact form below, email, or LinkedIn. I typically respond within 24 hours.", q3: "What technologies do you know?", a3: "I'm proficient in computer operations, video editing (CapCut), graphic design (Canva), AI Prompting, and various digital financial platforms (stocks, forex, crypto).", q4: "Can you work remotely?", a4: "Absolutely. I'm experienced in remote collaboration and comfortable using various digital communication tools for effective team coordination." },
  techstack: { title: "Tech Stack", subtitle: "Skills and tools I work with.", innerRing: "Core Competencies", outerRing: "Tools & Technology", sales: "Sales", leadership: "Leadership", communication: "Communication", negotiation: "Negotiation", capcut: "Video Editing", canva: "Graphic Design", ai: "AI Prompting", finance: "Financial Market", computer: "Computer Ops", python: "Python Fundamental", softwareDev: "Software Dev Fundamental" },
  achievements: { title: "Achievements", subtitle: "Badges and milestones achieved.", unlocked: "Achievements Unlocked", unlockedBadge: "UNLOCKED", items: { firstSale: { title: "First Sale", desc: "Closed first deal" }, hundredClients: { title: "100 Clients", desc: "Served 100+ customers" }, topPerformer: { title: "Top Performer", desc: "Exceeded sales targets" }, teamLeader: { title: "Team Leader", desc: "Led team to success" }, negotiator: { title: "Sharp Negotiator", desc: "Mastered negotiation skills" }, quickLearner: { title: "Quick Learner", desc: "Adapted to AI & digital tools" } } },
  shortcuts: { title: "Keyboard Shortcuts", theme: "Toggle Theme", language: "Toggle Language", sections: "Navigate Sections", palette: "Command Palette" },
  konami: { activated: "\ud83d\udd13 KONAMI CODE ACTIVATED", hackerMode: "HACKER MODE" },
  commandPalette: { title: "Commands", search: "Search commands...", navGroup: "Navigation", actionsGroup: "Actions", goHero: "Go to Hero", goAbout: "Go to About", goExperience: "Go to Experience", goContact: "Go to Contact", goFaq: "Go to FAQ", goTechstack: "Go to Tech Stack", goAchievements: "Go to Achievements", toggleTheme: "Toggle Theme", switchLang: "Switch Language", downloadCV: "Download CV", scrollTop: "Scroll to Top", hint: "\u2191\u2193 Navigate \u00b7 \u21b5 Select \u00b7 Esc Close" },
  ambientSound: { tooltip: "Ambient Sound" },
  themeCustomizer: { title: "Color Theme", presets: "Theme Presets", cyberpunk: "Cyberpunk", bloomberg: "Bloomberg", midnight: "Midnight", cyan: "Neon Cyan", magenta: "Neon Magenta", purple: "Neon Purple", reset: "Reset" },
  footer: { tagline: "Sales \u00b7 Leadership \u00b7 Communication", rights: "All rights reserved.", backToTop: "Back to top", online: "Online", builtWith: "Built with" },
}

type Translations = typeof id
const translations: Record<string, Translations> = { id, en }

function getNestedValue(obj: unknown, path: string): string {
  if (!obj || typeof obj === 'string') return typeof obj === 'string' ? obj : path
  const keys = path.split('.')
  let current: unknown = obj
  for (const key of keys) {
    if (current && typeof current === 'object' && key in current) {
      current = (current as Record<string, unknown>)[key]
    } else { return path }
  }
  return typeof current === 'string' ? current : path
}

interface LanguageState { lang: 'id' | 'en'; setLang: (lang: 'id' | 'en') => void; toggleLang: () => void; t: (key: string) => string }

export const useLanguageStore = create<LanguageState>((set, get) => ({
  lang: 'id',
  setLang: (lang) => { if (typeof window !== 'undefined') localStorage.setItem('lang', lang); set({ lang }) },
  toggleLang: () => { const n = get().lang === 'id' ? 'en' : 'id'; get().setLang(n) },
  t: (key: string) => { const { lang } = get(); const data = translations[lang]; if (!data) return key; return getNestedValue(data, key) },
}))